services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - '$PWD/../data/grafana:/var/lib/grafana'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - '$PWD/../resources/prometheus.yml:/etc/prometheus/prometheus.yml'

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    ports:
      - '9100:9100'
    volumes:
      - '/:/host:ro,rslave'

# TEST ON LINUX
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor
#    container_name: cadvisor
#    restart: unless-stopped
#    ports:
#      - '8080:8080'
#    volumes:
#      - '/:/rootfs:ro'
#      - '/var/run:/var/run:ro'
#      - '/sys:/sys:ro'
#      - '/var/lib/docker/:/var/lib/docker:ro'
#      - '/dev/disk/:/dev/disk:ro'
#    privileged: true
#    devices:
#      - '/dev/kmsg'

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    volumes:
      - '$PWD/../data/loki:/loki'
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    container_name: promtail
    restart: unless-stopped
    ports:
      - '9080:9080'
    volumes:
      - '$PWD/../resources/promtail.yml:/etc/promtail/promtail.yml'
      - '$PWD/../data/promtail:/promtail'
    command: -config.file=/etc/promtail/promtail.yml